# Generated by Django 3.2.4 on 2021-08-03 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20210803_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopuser',
            old_name='activation_key_expires',
            new_name='activation_key_created',
        ),
    ]
